"""new migrations

Revision ID: 1adef565ac4a
Revises: 2440cc8e4f99
Create Date: 2023-05-16 17:25:20.138669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1adef565ac4a'
down_revision = '2440cc8e4f99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
