"""new migrations

Revision ID: 2440cc8e4f99
Revises: b91b527f20bc
Create Date: 2023-05-16 16:40:17.945125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2440cc8e4f99'
down_revision = 'b91b527f20bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('size_product_id_fkey', 'size', type_='foreignkey')
    op.drop_column('size', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('size', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('size_product_id_fkey', 'size', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
