"""new migrations

Revision ID: 70dc7b71d42f
Revises: 1adef565ac4a
Create Date: 2023-05-17 22:56:40.524242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70dc7b71d42f'
down_revision = '1adef565ac4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
