"""update and add new tables

Revision ID: a26a5c1d81b1
Revises: 868c58c23af1
Create Date: 2023-05-14 10:38:34.146272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26a5c1d81b1'
down_revision = '868c58c23af1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('size_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_size_id'), 'product_size', ['id'], unique=False)
    op.add_column('product', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('product_image', 'default')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_image', sa.Column('default', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('product', 'image_url')
    op.drop_index(op.f('ix_product_size_id'), table_name='product_size')
    op.drop_table('product_size')
    op.drop_table('size')
    # ### end Alembic commands ###
