"""new migrations

Revision ID: a4552fc4ef41
Revises: 70dc7b71d42f
Create Date: 2023-05-17 23:34:12.237578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4552fc4ef41'
down_revision = '70dc7b71d42f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'stock')
    op.add_column('size', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('size', sa.Column('stock', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'size', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'size', type_='foreignkey')
    op.drop_column('size', 'stock')
    op.drop_column('size', 'product_id')
    op.add_column('product', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
