"""new migrations

Revision ID: b91b527f20bc
Revises: 5d353c8c4bce
Create Date: 2023-05-16 16:26:30.687885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91b527f20bc'
down_revision = '5d353c8c4bce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('size', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'size', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'size', type_='foreignkey')
    op.drop_column('size', 'product_id')
    # ### end Alembic commands ###
