"""New Migrations

Revision ID: b9dab0b8921b
Revises: 59bf4278f103
Create Date: 2023-05-15 22:26:35.618755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9dab0b8921b'
down_revision = '59bf4278f103'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
