"""New Migration

Revision ID: c1a5f211603d
Revises: 6fe6e431b6a3
Create Date: 2023-05-10 23:01:41.851656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a5f211603d'
down_revision = '6fe6e431b6a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
