"""new migrations

Revision ID: d4ab199ffa0e
Revises: eee970ebbe9d
Create Date: 2023-05-18 11:09:49.301767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ab199ffa0e'
down_revision = 'eee970ebbe9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
