"""new migrations

Revision ID: eee970ebbe9d
Revises: f2e040e6088d
Create Date: 2023-05-18 02:38:21.896645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee970ebbe9d'
down_revision = 'f2e040e6088d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'image', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_column('image', 'product_id')
    # ### end Alembic commands ###
