"""new migrations

Revision ID: f2e040e6088d
Revises: a4552fc4ef41
Create Date: 2023-05-18 01:52:59.594067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2e040e6088d'
down_revision = 'a4552fc4ef41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_image_id', table_name='product_image')
    op.drop_table('product_image')
    op.drop_index('ix_product_size_id', table_name='product_size')
    op.drop_table('product_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_size',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('size_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='product_size_product_id_fkey'),
    sa.ForeignKeyConstraint(['size_id'], ['size.id'], name='product_size_size_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_size_pkey')
    )
    op.create_index('ix_product_size_id', 'product_size', ['id'], unique=False)
    op.create_table('product_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], name='product_image_image_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='product_image_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_image_pkey')
    )
    op.create_index('ix_product_image_id', 'product_image', ['id'], unique=False)
    # ### end Alembic commands ###
